# WellRested Plugin Configuration

# Saturation effect settings
saturation:
  # Duration in seconds
  duration: 15
  # Amplifier level (0 = level I, 1 = level II, etc.)
  amplifier: 1

# Messages
messages:
  # Message shown when player wakes up
  well-rested: "&aYou got a very good sleep, and now you're well rested!"